/*Takes a given encoded file based on huffman encoding standards and 
 * decompresses to recreate the original file*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include "huff.h"

Tuple* freqlist;
Node* list;

int num;
int freqTotal = 0;

/*Reads the tree generated by the header to print the encoded chars*/
void readNewTree(int infile, int outfile, 
unsigned char buffer[], int bufLoc, int bytes) { 
    int i;
    char byte;
    unsigned char outbuffer[BUFFER_SIZE];
    Node* head = list;
    int written = 0;
    int j = 0;
    /*Special case for one char*/
    if(num+1 == 1) {
        for(i=0;i < list[0].freq; i++) {
            outbuffer[i] = list[0].c;
            j++;
            if(j >= BUFFER_SIZE) {
                write(outfile, outbuffer, sizeof(outbuffer)); 
                /*add error checking*/
                memset(outbuffer, 0, sizeof(outbuffer));
                j=0;
            }
        }
    }
    while(bytes > 0) {
        for(; bufLoc < bytes; bufLoc++) {
            byte = buffer[bufLoc];
            i = 7;
            while (i >= 0) {
                if ((byte >> i) & 1) {
                    list = list->right;
                    i--;
                } else {
                    list = list->left;
                    i--;
                }
                if(list->left == NULL && list->right == NULL) {
                    outbuffer[j] = list->c;
                    list = head;
                    j++;
                    written++;
                } if(j >= BUFFER_SIZE) {
                    write(outfile, outbuffer, sizeof(outbuffer)); 
                    /*add error checking*/
                    memset(outbuffer, 0, sizeof(outbuffer));
                    j=0;
                }
                if (written >= freqTotal) {
                    break;
                }
            }
        }
        bufLoc=0;
        bytes = read(infile, buffer, sizeof(buffer));
    }
    if(j>=0) {
        write(outfile, outbuffer, j);
    }
}

/*Builds the tree based on the freq list from the header*/
void buildTree(unsigned char buffer[]) {
    int i;
    for(i = 0; i < CHAR_SIZE; i++) {
        if(freqlist[i].c != -1 && freqlist[i].freq != 0) {
            list = createLinked(list, &freqlist[i]);
        }
    }
    list = combineTree(list);
}

/*Reads header and creates freqlist based on it*/
int readHeader(unsigned char buffer[], int fileLoc) {
    int j;
    num = buffer[fileLoc];
    fileLoc++;
    for(j = 0; j < num+1; j++) {
        freqlist[j].c = buffer[fileLoc];
        freqlist[j].freq = (buffer[fileLoc+1] << 24) + 
        (buffer[fileLoc+2] << 16) + (buffer[fileLoc+3] << 8) + 
        buffer[fileLoc+4];
        freqTotal += freqlist[j].freq;
        fileLoc+=5;
    } 
    return fileLoc;
}

/*reads chunks of file and calls other functions*/
void readCoded(int infile, int outfile) {
    ssize_t bytes;
    unsigned char buffer[BUFFER_SIZE];
    int bufLoc = 0;
    bytes = read(infile, buffer, sizeof(buffer));
    if (bytes == -1) {
            perror("read");
            exit(EXIT_FAILURE);
        }
    bufLoc = readHeader(buffer, bufLoc);
    qsort(freqlist, CHAR_SIZE, sizeof(*freqlist), cmpfunc);
    buildTree(buffer);
    readNewTree(infile, outfile, buffer, bufLoc, bytes);
}

/*Opens input files and error checks*/
int openInFile(char const filename[]) {
    int file;
    off_t size;
    file = open(filename, O_RDONLY);
    if(file == -1) {
        perror("open");
        exit(EXIT_FAILURE);
    }
    size = lseek(file, 0, SEEK_END);
    if(size == 0) {
        close(file);
        free(freqlist);
        return -1;
    } lseek(file, 0, SEEK_SET);
    return file;
}


/*Opens output files and error checks*/
int openOutFile(char const filename[]) {
    int file;
    file = open(filename, O_WRONLY | O_TRUNC | O_CREAT, 0644);
    if(file == -1) {
        perror("open");
        exit(EXIT_FAILURE);
    }
    return file;
}

/*Handles command line aruments and generally calling other functions*/
int main(int argc, char const *argv[]) {
    int infile;
    int outfile;
    int i;
    if(!(freqlist = malloc(sizeof(Tuple) * CHAR_SIZE))) {
        perror("malloc");
        exit(EXIT_FAILURE);
    }
    for(i = 0; i < CHAR_SIZE; i++) {
        freqlist[i].c = -1;
        freqlist[i].freq = 0;
    }
    if(argc == 2 || (argc == 3 && *argv[1] == '-')) {
        outfile = openOutFile(argv[1]);
        infile = 0;
    } else if(argc == 3) {
        outfile = openOutFile(argv[2]);
        infile = openInFile(argv[1]);
        if(infile == -1) /*remove the outfile part*/
            return 0;
    } else {
       printf("%s", "Usage ./hdecode [inFile | '-'] [outFile]");
       return 0;
    }
    readCoded(infile, outfile);
    free(freqlist);
    freeTree(list);
    close(infile);
    close(outfile);
    return 0;
}
